### ISSUE TITLE
Error: can't read /var/mail/actions_ips

### ISSUE THREAD

**Issue by PrateekKhatri** [andymckay/actions-ips#8]
I am trying to get the IP of GitHub runner. Below is the command I have added in my GitHub workflow file:

- name: GetIP
        run: |
          pip install actions-ips
          from actions_ips import ips
          ips.cidrs()

I am getting below error: 
from: can't read /var/mail/actions_ips

Could you please help me with this error?

**Comment by andymckay** [comment]
I don't fully understand the context but this library is Python. 

First it will get you the IP of every possible IP, not the IP of the actual runner you are using.

Secondly that code won't work because:

```
pip install actions-ips 👈 that's bash
from actions_ips import ips 👈 that's python
ips.cidrs() 👈 that's python
```

You'd need to write a script, a `.py` file and run that to get the complete list.

Hope that helps.

**Comment by PrateekKhatri** [comment]
Hi,

Thanks for clarification.

Is there a way we can find particular IP of GitHub runner instead of getting list of IPs.
